# Development Configuration
# Optimized for development and testing

server:
  port: "8080"
  host: "localhost"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

detector:
  window_size: 100  # Smaller window for faster testing
  threshold: 2.5    # Lower threshold for more anomaly detection

monetization:
  enabled: true
  base_price: 0.0001  # Lower price for testing
  complexity_multiplier: 0.05
  output_file: "dev_pov_records.jsonl"

validation:
  enabled: false  # Disable for easier testing
  max_value: 1000000
  min_value: -1000000
  max_timestamp: 2147483647
  min_timestamp: 1609459200
  allowed_source: "*"

rate_limit:
  enabled: false  # Disable for development
  requests_per_second: 10000
  burst_size: 1000